version: "3"
services:
    # MySQL 5.7: https://hub.docker.com/_/mysql/
    mysql:
        container_name: mysql
        image: mysql:5.7
        command: mysqld --sql_mode="NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
        restart: always
        privileged: true
        environment:
            MYSQL_ROOT_PASSWORD: "ezhan123"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "ezhan123"
            #MYSQL_DATABASE: "test"
        volumes:
            - /home/xcntw/docker/mysql:/var/lib/mysql
        ports:
            - "13306:3306"

    # Redis 3.2.10: https://hub.docker.com/_/redis/
    redis:
        container_name: redis
        image: redis:3.2.10
        command: redis-server --requirepass ezhan123
        restart: always
        privileged: true
        volumes:
            - /home/xcntw/docker/redis:/data
        ports:
            - "16379:6379"

    #内网 registry-internal.cn-hangzhou.aliyuncs.com/pangxiaobo/php7_nginx:v1
    nginx:
        container_name: nginx
        image: registry.cn-hangzhou.aliyuncs.com/pangxiaobo/php7_nginx:v1
        restart: always
        privileged: true
        links:
            - mysql
            - redis
        volumes:
            - /home/xcntw/docker/ezhan:/var/www/app
        ports: 
            - "8081:80"
            - "8082:8082"
            - "8083:8083"
            - "8084:8084"
            - "8085:8085"
            - "8086:8086"
            - "10443:443"
            - "10122:6022"